In [2]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.0521, 0.7710, 0.8648],
        [0.2096, 0.8417, 0.2557],
        [0.1497, 0.9253, 0.6093],
        [0.2775, 0.3009, 0.9422],
        [0.9579, 0.0613, 0.8080]])


In [3]:
if torch.cuda.is_available():
    tensor=tensor.to('cuda')

In [23]:
tensor = torch.ones(4,4)
print("First row:",tensor[0])
print("First column:",tensor[:,0])
print("Second column:",tensor[:,1])
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Second column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [16]:
tensor1 = torch.ones(4,4)
tensor2 = torch.zeros(4,4)

t1 = torch.cat([tensor1,tensor2], dim=1)        #텐서 합치기 -> troch.cat
print(t1)

tensor([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]])


In [17]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)  # 결과를 y3에 저장

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [18]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
agg = tensor.sum()  # 텐서의 모든 원소를 합산
agg = tensor.sum(0)  # 텐서의 모든 원소를 합산  ->dim 0 방향으로 합 # (행 방향)
agg = tensor.sum(1)  # 텐서의 모든 원소를 합산  ->dim 1 방향으로 합 # (열 방향)
# agg = tensor.sum(2)  # 텐서의 모든 원소를 합산  # ->dim 2 방향으로 합 # (3차원 텐서에서 사용)agg = tensor.sum()  # 텐서의 모든 원소를 합산
agg = tensor.sum()  # 텐서의 모든 원소를 합산
print(agg)
agg_item = agg.item()
print(agg, type(agg))
print(agg_item, type(agg_item))

tensor(12.)
tensor(12.) <class 'torch.Tensor'>
12.0 <class 'float'>


In [42]:
print(tensor)
tensor.add_(5)  #tensor.add(5)랑 무슨 차이가 있을까? add()는 메모리에 새로운 변수를 할당하지만,
                #add_()는 기존 메모리를 재사용해서 값을 변경함. 이를 in-place operation이라고 함.

tensor([[16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.]])


tensor([[21., 20., 21., 21.],
        [21., 20., 21., 21.],
        [21., 20., 21., 21.],
        [21., 20., 21., 21.]])

In [49]:
t = torch.ones(5)
n = t.numpy()   # 텐서를 넘파이 배열로 변환  bridge 라고 부름
print("t: ", t)
print("n: ",n)

t:  tensor([1., 1., 1., 1., 1.])
n:  [1. 1. 1. 1. 1.]


In [50]:
t.add_(1)   # 텐서에 1을 더함 (in-place operation), 메모리 재사용
print("t: ",t)
print("n: ",n)  # 넘파이 배열도 변경됨, 텐서와 넘파이 배열은 메모리를 공유함 -> 매우 중요

t:  tensor([2., 2., 2., 2., 2.])
n:  [2. 2. 2. 2. 2.]
